### ISSUE TITLE
Action plan for Marketplace

### ISSUE THREAD

**Issue by fgeyer16** [clarity-h2020/marketplace#16]
Todo list for the marketplace

**Preparation**

- [x] Create Profiles #2 
- [x] Harmonise marketplace entities #3 
- [x] Create solution offers #1 
- [x] solution offers Taxonomy #5 
- [x] sectors taxonomy #6 
- [x] Projects on marketplace #11 
...
**Integration**

- [ ] Taxonomy harmonisation #9 
- [x] Content exposure to other drupal instances #13 (how to clear implementation on need)
- [x] Show content of other drupal instances #12 (how to clear implementation on need)
- [x] Projects on market place #15 
- [x] Solutions and show cases on marketplace #14 
- [x] Single Sign on #10 
...

**Comment by p-a-s-c-a-l** [comment]
Any status updates here? We want to [encourage solution providers to describe their solution offers in the marketplace](https://github.com/clarity-h2020/docker-drupal/issues/84#issuecomment-516833115). When will this be possible?

**Comment by p-a-s-c-a-l** [comment]
> Any status updates here? We want to [encourage solution providers to describe their solution offers in the marketplace](https://github.com/clarity-h2020/docker-drupal/issues/84#issuecomment-516833115). When will this be possible?

**Comment by p-a-s-c-a-l** [comment]
Is this still relevant? What about the [other issues](https://github.com/clarity-h2020/marketplace/issues)? Can you please check and close the other issues @fgeyer16 ?
